name: Modelibot

services:
  modelibot_container:
    image: ros_lslidar
    build:
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${_ROS_USER:?Please set an .env file with _ROS_USER}
    privileged: true
    environment:
      DISPLAY: ${DISPLAY:-:0}
      XDG_RUNTIME_DIR: /run/user/${UID:-1000}
      ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST
      ROS_STATIC_PEERS: $_ROS_STATIC_PEERS
      ROS_DOMAIN_ID: ${_ROS_DOMAIN_ID:-0}
      #ROS_DISCOVERY_SERVER: $_DISCOVERY_SERVER_LIST
      #FASTDDS_BUILTIN_TRANSPORTs: "LARGE_DATA"
      #ROS_SUPER_CLIENT: ${_ROS_SUPER_CLIENT:-false}
      # RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      #FASTRTPS_DEFAULT_PROFILES_FILE=/home/$_ROS_USER/fastdds_default_profiles.xml
    volumes:
      - ./:/home/$_ROS_USER/ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - /dev/dri:/dev/dri:cached
      - ~/.Xauthority:/home/$_ROS_USER/.Xauthority
      - /dev/input:/dev/input:bind
      - /dev:/dev:bind
      - /run/user/${UID:-1000}:/run/user/${UID:-1000}
    network_mode: "host"
    ipc: "host"
    pid: "host"
    user: $_ROS_USER
    tty: true
    #command: "ros2 launch lslidar_driver lslidar_launch.py"